# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: API Integration Workflow

on:
  push:
    branches:
      - main

jobs:
  api-integration:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release

    - name: Call GET API and capture response
      run: |
        echo "Calling GET API"
        $GET_RESPONSE = curl -X GET "https://your-api-url/get-endpoint" -s -w "%{http_code}" -o get_response.txt
        $GET_STATUS_CODE = (Get-Content get_response.txt | Select-Object -Last 1)
        $GET_RESPONSE_BODY = Get-Content get_response.txt -Raw
        echo "GET Status Code: $GET_STATUS_CODE"
        echo "GET Response Body: $GET_RESPONSE_BODY"

    - name: Call POST API and capture response
      run: |
        echo "Calling POST API"
        $POST_RESPONSE = curl -X POST "https://your-api-url/post-endpoint" -H "Content-Type: application/json" -d '{"key1":"value1", "key2":"value2"}' -s -w "%{http_code}" -o post_response.txt
        $POST_STATUS_CODE = (Get-Content post_response.txt | Select-Object -Last 1)
        $POST_RESPONSE_BODY = Get-Content post_response.txt -Raw
        echo "POST Status Code: $POST_STATUS_CODE"
        echo "POST Response Body: $POST_RESPONSE_BODY"
