# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: API Integration Workflow

on:
  push:
    branches:
      - main

jobs:
  api-integration:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release

    - name: Call POST API and capture response
      run: |
        # PowerShell syntax for invoking POST request
        
        # Check if the Ngrok tunnel is up
        $ngrokStatus = Invoke-RestMethod -Uri "http://localhost:4040/api/tunnels" -Method Get -ErrorAction SilentlyContinue
        if ($ngrokStatus -eq $null) {
          Write-Error "Ngrok tunnel is not active. Please ensure Ngrok is running."
          exit 1
        }

        $uri = "  https://0451-47-247-10-34.ngrok-free.app/api/fhir/patient"
        $headers = @{
          "Content-Type" = "application/json"
        }
        $body = @{
          resourceType = "Patient"
          name = @(
            @{
              use = "official"
              family = "Doe"
              given = @("John")
            }
          )
          gender = "male"
          birthDate = "1990-01-01"
        } | ConvertTo-Json

        try {
          # Make the POST request
          $response = Invoke-RestMethod -Uri $uri -Method Post -Headers $headers -Body $body
          Write-Output "Response: $($response)"
        } catch {
          Write-Error "Failed to make POST request: $_"
          exit 1
        }


